version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "uv"
    directory: "/"
    insecure-external-code-execution: allow
    schedule:
      interval: "daily"
    groups:
      python:
        patterns:
          - "*"
