"""empty message

Revision ID: b632cb0e65fd
Revises:
Create Date: 2025-08-06 19:17:18.682480

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b632cb0e65fd"  # pragma: allowlist secret
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=False)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_index(
        op.f("ix_user_username"), "user", ["username"], unique=False
    )
    op.create_table(
        "user_event_stream",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("aggregate_id", sa.UUID(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "USER_CREATED",
                "USER_UPDATED",
                "USER_DELETED",
                "PASSWORD_CHANGED",
                name="eventtype",
            ),
            nullable=False,
        ),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "data", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "aggregate_id",
            "revision",
            name="uq_user_event_stream_aggregate_revision",
        ),
    )
    op.create_index(
        "idx_user_event_stream_aggregate_timestamp",
        "user_event_stream",
        ["aggregate_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_event_stream_aggregate_id"),
        "user_event_stream",
        ["aggregate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_event_stream_id"),
        "user_event_stream",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_event_stream_id"), table_name="user_event_stream"
    )
    op.drop_index(
        op.f("ix_user_event_stream_aggregate_id"),
        table_name="user_event_stream",
    )
    op.drop_index(
        "idx_user_event_stream_aggregate_timestamp",
        table_name="user_event_stream",
    )
    op.drop_table("user_event_stream")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
