name: CI on PRs

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  id-token: write
  contents: write
  issues: write
  checks: write
  pull-requests: write


jobs:
  precommit:
    uses: ./.github/workflows/precommit.yml

  test:
    uses: ./.github/workflows/test.yml
